name: Trigger auto deployment for fastapi-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fastapi-app-AutoDeployTrigger-03d93980-5ce7-425b-9dd6-db52b167c6eb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FASTAPIAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FASTAPIAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FASTAPIAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: dockerreg5271.azurecr.io
          registryUsername: ${{ secrets.FASTAPIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FASTAPIAPP_REGISTRY_PASSWORD }}
          containerAppName: fastapi-app
          resourceGroup: tr-ma-containers-rg
          imageToBuild: dockerreg5271.azurecr.io/fastapi-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


